# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 75ed0fb8b78ef9dfd3d3ea189dd9f7c388d92cd118945c85977df351c4957f7a81c601badb60a2eeee2508026704262ef4c4f2ae9028aeaa2bc3b165ee17dfb4

test:
  secret_key_base: 9f191702b6e06689842278a9c45954ea11d205d5ffebfec7b2b29c5bcd8c1ba937b6b4a35f074416dc3e7bf982bbd19c7fbd9c5f950e09a3cee06efb45dcd5ad

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
